name: Deploy Angular to S3

on:
  push:
    branches:
      - front-s3   

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Aquí bajamos el código.
      - name: Checkout code
        uses: actions/checkout@v3

      # Instala el node.js para angular.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instalar las librerías del proyecto.
      - name: Install dependencies
        run: npm ci

      # Aquí se construye la página con el dist.
      - name: Build Angular App
        run: npm run build

      # Se sube a aws s3.
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: frontend-patitas-v1      # Name del bucket.
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'dist/PATITAS/browser'      # Carpeta de salida.